### ISSUE TITLE
Timer does not start if AutoSplit is openned from openning LiveSplit

### ISSUE THREAD

**Issue by Avasam** [KaDiWa4/LiveSplit.AutoSplitIntegration#1]
Steps:
1. Configure AutoSplit Integration to automatically open AutoSplit
2. Close LiveSplit
3. Open LiveSplit (AutoSplit starts up automatically)
4. Start the Timer (AutoSplit does not start)

It does work if I instead open AutoSplit from Right Click > Control > Start AutoSplit

**Comment by kadiwa4** [comment]
Should hopefully be fixed now

**Comment by Avasam** [comment]
@KaDiWa4 It does seem to be fixed thank you
