### ISSUE TITLE
The update prompt always appear

### ISSUE THREAD

**Issue by Avasam** [KaDiWa4/LiveSplit.AutoSplitIntegration#2]
I get LiveSplit's update prompt everytime I open it.
Despite clicking "Yes" and despite re-downloading the .dll and manually placing it under LiveSplit/Components
It also seems to get installed in the root of LiveSplit folder.

![image](https://user-images.githubusercontent.com/1350584/92553875-19998700-f232-11ea-88e9-6a5a937e058a.png)

**Comment by kadiwa4** [comment]
:)
I didn’t know how the update system worked so I just guessed, but that shouldn't be hard to fix

Thanks for making these issues though

**Comment by kadiwa4** [comment]
I think I fixed it. Now the update prompt won't appear at all because I changed the XML's URL so you have to do this update manually

**Comment by Avasam** [comment]
I am no longer receiving an update notice despite already being updated 👍

> Thanks for making these issues though

Of course. You need someone to report them to be aware! I am glad you're actually supporting it and can't wait to see your features be part of the main repo. (as having to compile and change the icon yourself is a bit obscure for some). This entire project has been a game-changer.
